name: Release

on:
  workflow_dispatch:

permissions: {}

jobs:
  release-perform:
    name: Release - Perform
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    permissions:
      contents: write # Required to publish a GitHub release
      issues: write # Required to comment on released issues
      pull-requests: write # Required to comment on released pull requests

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            objects.githubusercontent.com:443
            uploads.github.com:443
            repo.maven.apache.org:443
            jitpack.io:443
            repo.papermc.io:443
            api.nuget.org:443
            registry.npmjs.org:443

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0 # Required by semantic-release

      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: lts/jod
          cache: npm
          cache-dependency-path: .github/release/package-lock.json

      - name: Setup Java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: 17
          distribution: temurin

      - name: Install semantic-release
        working-directory: .github/release/
        run: npm clean-install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MAVEN_ARGS: --batch-mode -Dstyle.color=always
        working-directory: .github/release/
        run: npx --no-install semantic-release
